In [2]:
pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.6-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in f:\py\anaconda\envs\eng213\lib\site-packages (from statsmodels) (2.2.5)
Collecting scipy!=1.9.2,>=1.8 (from statsmodels)
  Downloading scipy-1.15.3-cp310-cp310-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in f:\py\anaconda\envs\eng213\lib\site-packages (from statsmodels) (2.3.3)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging>=21.3 in f:\py\anaconda\envs\eng213\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in f:\py\anaconda\envs\eng213\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in f:\py\anaconda\envs\eng213\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in f:\py\anaconda\envs\eng213\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.3)
Requirement already satisfied: six>=1.5 in f:\py\anaconda\envs\eng213\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.14.6-cp310-cp310-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.6 MB 13.0 MB/s eta 0:00:01
   ------------------- -------------------- 4.7/9.6 MB 12.4 MB/s eta 0:00:01
   ------------------------------------ --- 8.7/9.6 MB 14.5 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 14.5 MB/s  0:00:00
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading scipy-1.15.3-cp310-cp310-win_amd64.whl (41.3 MB)
   ---------------------------------------- 0.0/41.3 MB ? eta -:--:--
   ---- ----------------------------------- 4.7/41.3 MB 22.0 MB/s eta 0:00:02
   ---------- ----------------------------- 10.7/41.3 MB 25.8 MB/s eta 0:00:02
   --------------- ------------------------ 16.0/41.3 MB 25.2 MB/s eta 0:00:02
   --------------------- ------------------ 22.0/41.3 MB 26.3 MB/s eta 0:00:01
   --------------------------- ------------ 28.8/41.3 MB 27.3 MB/s eta 0:00:01
   ----------------------------------- ---- 36.7/41.3 MB 29.2 MB/s eta 0:00:01
   ---------------------------------------- 41.3/41.3 MB 28.5 MB/s  0:00:01
Installing collected packages: scipy, patsy, statsmodels

   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ---------------------------------------- 0/3 [scipy]
   ------------- -------------------------- 1/3 [patsy]
   ------------- -------------------------- 1/3 [patsy]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   -------------------------- ------------- 2/3 [statsmodels]
   ---------------------------------------- 3/3 [statsmodels]

Successfully installed patsy-1.0.2 scipy-1.15.3 statsmodels-0.14.6
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

df = pd.read_csv('icecreamsales.csv')

In [4]:
df

         Month   Sales
0   2019-01-31  412.92
1   2019-02-28  341.00
2   2019-03-31  324.47
3   2019-04-30  320.42
4   2019-05-31  277.35
5   2019-06-30  192.90
6   2019-07-31  259.00
7   2019-08-31  266.59
8   2019-09-30  297.42
9   2019-10-31  341.29
10  2019-11-30  364.32
11  2019-12-31  437.26
12  2020-01-31  382.83
13  2020-02-29  333.35
14  2020-03-31  311.10
15  2020-04-30  277.51
16  2020-05-31  269.88
17  2020-06-30  206.41
18  2020-07-31  246.26
19  2020-08-31  250.78
20  2020-09-30  236.18
21  2020-10-31  347.97
22  2020-11-30  385.93
23  2020-12-31  365.88
24  2021-01-31  428.09
25  2021-02-28  290.00
26  2021-03-31  301.14
27  2021-04-30  265.79
28  2021-05-31  270.66
29  2021-06-30  235.71
30  2021-07-31  243.10
31  2021-08-31  278.51
32  2021-09-30  277.81
33  2021-10-31  275.53
34  2021-11-30  349.56
35  2021-12-31  395.08

In [5]:
# convert Date string to datetime object
df['Month'] = pd.to_datetime(df['Month'], format = '%Y-%m-%d')

# assigning the results to all rows from the 'Date' column
# df.loc[:, 'Date'] = pd.to_datetime(df['Date'], format='%m/%d/%Y')

# df2 = df.copy()
# df2['Date'] = pd.to_datetime(df2['Date'], format='%m/%d/%Y')
# df = df2

In [6]:
# create time index for regression analysis
df['Time_Index'] = np.arange(len(df)) + 1

In [7]:
df

        Month   Sales  Time_Index
0  2019-01-31  412.92           1
1  2019-02-28  341.00           2
2  2019-03-31  324.47           3
3  2019-04-30  320.42           4
4  2019-05-31  277.35           5
5  2019-06-30  192.90           6
6  2019-07-31  259.00           7
7  2019-08-31  266.59           8
8  2019-09-30  297.42           9
9  2019-10-31  341.29          10
10 2019-11-30  364.32          11
11 2019-12-31  437.26          12
12 2020-01-31  382.83          13
13 2020-02-29  333.35          14
14 2020-03-31  311.10          15
15 2020-04-30  277.51          16
16 2020-05-31  269.88          17
17 2020-06-30  206.41          18
18 2020-07-31  246.26          19
19 2020-08-31  250.78          20
20 2020-09-30  236.18          21
21 2020-10-31  347.97          22
22 2020-11-30  385.93          23
23 2020-12-31  365.88          24
24 2021-01-31  428.09          25
25 2021-02-28  290.00          26
26 2021-03-31  301.14          27
27 2021-04-30  265.79          28
28 2021-05-31  270.66          29
29 2021-06-30  235.71          30
30 2021-07-31  243.10          31
31 2021-08-31  278.51          32
32 2021-09-30  277.81          33
33 2021-10-31  275.53          34
34 2021-11-30  349.56          35
35 2021-12-31  395.08          36

In [8]:
# Linear Regression using ols
model = smf.ols(formula='Sales ~ Time_Index', data=df).fit()

In [9]:
# Forecast sales for the next year 12 months
df_forecast = pd.DataFrame({
    'Month': pd.date_range(start='2022-01-01', periods=12, freq='M'),
    'Time_Index': np.arange(37, 49)
})

C:\Users\LENOVO-PC\AppData\Local\Temp\ipykernel_57660\1539330755.py:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  'Month': pd.date_range(start='2022-01-01', periods=12, freq='M'),

In [10]:
df_forecast

        Month  Time_Index
0  2022-01-31          37
1  2022-02-28          38
2  2022-03-31          39
3  2022-04-30          40
4  2022-05-31          41
5  2022-06-30          42
6  2022-07-31          43
7  2022-08-31          44
8  2022-09-30          45
9  2022-10-31          46
10 2022-11-30          47
11 2022-12-31          48

In [11]:
df_forecast['Forecasted_Sales'] = model.predict(df_forecast)

In [12]:
df_forecast

        Month  Time_Index  Forecasted_Sales
0  2022-01-31          37        296.614127
1  2022-02-28          38        296.040716
2  2022-03-31          39        295.467306
3  2022-04-30          40        294.893895
4  2022-05-31          41        294.320485
5  2022-06-30          42        293.747074
6  2022-07-31          43        293.173664
7  2022-08-31          44        292.600253
8  2022-09-30          45        292.026843
9  2022-10-31          46        291.453432
10 2022-11-30          47        290.880021
11 2022-12-31          48        290.306611

In [13]:
# Calculate the average monthly sales for the three years
avg_monthly_sales = df['Sales'].groupby(df['Month'].dt.month).mean()

In [14]:
avg_monthly_sales

Month
1     407.946667
2     321.450000
3     312.236667
4     287.906667
5     272.630000
6     211.673333
7     249.453333
8     265.293333
9     270.470000
10    321.596667
11    366.603333
12    399.406667
Name: Sales, dtype: float64

In [15]:
# Calculate the overall average sales across all months
overall_avg_sales = df['Sales'].mean()

In [16]:
overall_avg_sales

np.float64(307.22222222222223)

In [17]:
# Calculate the seasonal index for each month
df_forecast['Month_Index'] = df_forecast['Month'].dt.month

In [18]:
df_forecast['Month_Index']

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
Name: Month_Index, dtype: int32

In [19]:
df_forecast['Seasonal_Index'] = df_forecast['Month_Index'].apply(lambda x: avg_monthly_sales[x] / overall_avg_sales)

In [20]:
df_forecast['Seasonal_Index']

0     1.327855
1     1.046311
2     1.016322
3     0.937128
4     0.887403
5     0.688991
6     0.811964
7     0.863523
8     0.880373
9     1.046788
10    1.193284
11    1.300058
Name: Seasonal_Index, dtype: float64

In [21]:
# Adjust the annual forecast using the seasonal index to get the seasonally adjusted forecast for each month
df_forecast['Seasonally_Adjusted_Forecast'] = df_forecast['Forecasted_Sales'] * df_forecast['Seasonal_Index']

df_forecast[['Month', 'Seasonally_Adjusted_Forecast']]

        Month  Seasonally_Adjusted_Forecast
0  2022-01-31                    393.860651
1  2022-02-28                    309.750667
2  2022-03-31                    300.289888
3  2022-04-30                    276.353442
4  2022-05-31                    261.180956
5  2022-06-30                    202.389078
6  2022-07-31                    238.046412
7  2022-08-31                    252.666932
8  2022-09-30                    257.092405
9  2022-10-31                    305.090080
10 2022-11-30                    347.102448
11 2022-12-31                    377.415393

In [22]:
# Choose the window size (e.g., 12 months)
window_size = 12

# Calculate the rolling moving average on the historical data
df['Moving_Avg'] = df['Sales'].rolling(window=window_size).mean()

# The Moving_Avg column will now contain the 12-month moving average of sales.

In [23]:
df

        Month   Sales  Time_Index  Moving_Avg
0  2019-01-31  412.92           1         NaN
1  2019-02-28  341.00           2         NaN
2  2019-03-31  324.47           3         NaN
3  2019-04-30  320.42           4         NaN
4  2019-05-31  277.35           5         NaN
5  2019-06-30  192.90           6         NaN
6  2019-07-31  259.00           7         NaN
7  2019-08-31  266.59           8         NaN
8  2019-09-30  297.42           9         NaN
9  2019-10-31  341.29          10         NaN
10 2019-11-30  364.32          11         NaN
11 2019-12-31  437.26          12  319.578333
12 2020-01-31  382.83          13  317.070833
13 2020-02-29  333.35          14  316.433333
14 2020-03-31  311.10          15  315.319167
15 2020-04-30  277.51          16  311.743333
16 2020-05-31  269.88          17  311.120833
17 2020-06-30  206.41          18  312.246667
18 2020-07-31  246.26          19  311.185000
19 2020-08-31  250.78          20  309.867500
20 2020-09-30  236.18          21  304.764167
21 2020-10-31  347.97          22  305.320833
22 2020-11-30  385.93          23  307.121667
23 2020-12-31  365.88          24  301.173333
24 2021-01-31  428.09          25  304.945000
25 2021-02-28  290.00          26  301.332500
26 2021-03-31  301.14          27  300.502500
27 2021-04-30  265.79          28  299.525833
28 2021-05-31  270.66          29  299.590833
29 2021-06-30  235.71          30  302.032500
30 2021-07-31  243.10          31  301.769167
31 2021-08-31  278.51          32  304.080000
32 2021-09-30  277.81          33  307.549167
33 2021-10-31  275.53          34  301.512500
34 2021-11-30  349.56          35  298.481667
35 2021-12-31  395.08          36  300.915000